[theme]
base = "dark"                    
primaryColor = "#0eaeb0"         
backgroundColor = "#040404"      
secondaryBackgroundColor = "#f66c24"  
textColor = "#FFFFFF"            
font = "sans serif"
